import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import Provider from "./_components/provider";
import { ClerkProvider } from "@clerk/nextjs";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const playfair_display=Playfair_Display({subsets:['latin']})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider>
    <html lang="en">
      <body
        className={playfair_display.className}
      >
        <Provider children></Provider>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
